### ISSUE TITLE
cannot import filterfalse 

### ISSUE THREAD

**Issue by DzoYee** [altf4/libmelee#28]
Any familiarity with this issue?
```
libmelee git:(master) python example.py
Traceback (most recent call last):
  File "example.py", line 2, in <module>
    import melee
  File "/Users/joeyleung/workspace/melee/libmelee/melee/__init__.py", line 10, in <module>
    from melee import menuhelper, techskill, framedata, stages, dtmreader
  File "/Users/joeyleung/workspace/melee/libmelee/melee/framedata.py", line 6, in <module>
    from itertools import filterfalse
ImportError: cannot import name filterfalse```

**Comment by altf4** [comment]
libmelee is Python3, that is probably it. Try running `python3 example.py`

Or else `./example.py`
